version: '2'
services:
  bot:
    build: .
#    ports:
#     - "5000:5000"
    volumes:
     - .:/usr/src/app
    depends_on:
     - redis
  redis:
    image: redis
    command: redis-server --appendonly yes
